import { StrictMode, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowRight, Clock3, Menu, Phone, ShieldCheck, Stethoscope, X } from 'lucide-react'
import './styles.css'

const services = [
  ['01', 'Root canal therapy', 'Relieve pain and preserve your natural tooth with precise, comfortable treatment.'],
  ['02', 'Retreatment', 'A careful second look for teeth that need additional endodontic attention.'],
  ['03', 'Microsurgery', 'Advanced surgical care when a non-surgical approach is not enough.'],
  ['04', 'Cracked teeth & trauma', 'Prompt evaluation and a clear plan for urgent dental injuries.'],
]
const nav = [['Home', '#top'], ['Meet the doctors', '#doctors'], ['Office', '#office'], ['Services', '#services'], ['New patients', '#patients'], ['Referring doctors', '#referring'], ['Contact us', '#contact'], ['Patient education', '#education']]

function ContactLink({ children = 'Contact us now' }) { return <a className="btn dark" href="#contact">{children} <ArrowRight size={17} /></a> }

function App() {
  const [menu, setMenu] = useState(false)
  const close = () => setMenu(false)
  return <div className="site">
    <div className="top"><div className="container top-in"><span>Northbrook's dedicated endodontic practice</span><a href="tel:8474801578"><Phone size={14} /> (847) 480-1578</a></div></div>
    <header><div className="container head-in"><a className="brand" href="#top" onClick={close} aria-label="North Shore Endodontics home"><img src="/assets/northshore-logo.webp" alt="North Shore Endodontics" /></a><nav className={menu ? 'open' : ''}>{nav.map(([label, href]) => <a key={href} href={href} onClick={close}>{label}</a>)}<a className="nav-cta" href="#contact" onClick={close}>Contact us now <ArrowRight size={16} /></a></nav><button className="menu" onClick={() => setMenu(!menu)} aria-expanded={menu} aria-label={menu ? 'Close navigation' : 'Open navigation'}>{menu ? <X /> : <Menu />}</button></div></header>
    <main id="top">
      <section className="hero"><div className="container hero-in"><div><p className="eyebrow light">Specialized care. Lasting confidence.</p><h1>Keep your natural smile <em>healthy.</em></h1><p className="lead">Expert endodontic care with a calm, personal approach—so you can get back to the moments that make you smile.</p><div className="actions"><a className="btn white" href="#contact">Contact us now <ArrowRight size={17} /></a><a href="#services" className="link light">Explore our services <ArrowRight size={16} /></a></div><div className="note"><ShieldCheck size={18} /> Proudly serving Northbrook and the North Shore</div></div><aside><small>A thoughtful next step</small><p>“You deserve to understand your care and feel comfortable with the plan.”</p><b /></aside></div></section>
      <section className="trust"><div className="container trust-in"><div><b>40+</b><span>years of combined<br />experience</span></div><div><b>01</b><span>specialty practice<br />for your comfort</span></div><div><b>100%</b><span>focused on saving<br />natural teeth</span></div><a href="#contact">Talk with our team <ArrowRight size={17} /></a></div></section>
      <section className="section container intro"><small className="eyebrow">A better endodontic experience</small><div><h2>Specialized care, delivered with <em>clarity.</em></h2><div><p>At North Shore Endodontics, we combine advanced technology with the kind of personal attention that makes a difference. From your first call to your final follow-up, you’ll know what to expect.</p><a className="link" href="#visit">What to expect <ArrowRight size={16} /></a></div></div></section>
      <section className="section services" id="services"><div className="container"><div className="heading"><div><small className="eyebrow">How we can help</small><h2>Focused treatment for<br /><em>complex problems.</em></h2></div><p>We treat the inside of the tooth, helping you preserve your natural smile with precise, conservative care.</p></div><div className="service-grid">{services.map(([number, title, text]) => <article key={title}><span>{number}</span><Stethoscope size={22} /><h3>{title}</h3><p>{text}</p><a href="#contact">Learn more <ArrowRight size={15} /></a></article>)}</div></div></section>
      <section className="section container doctors" id="doctors"><div><small className="eyebrow">Meet your doctors</small><h2>Experience you can <em>feel.</em></h2><p>Our doctors bring expertise, patience, and a shared belief that the best care starts with listening.</p><a className="link" href="#contact">Meet the team <ArrowRight size={16} /></a></div><div className="doctor-grid"><article className="doc one"><div><small>Endodontist</small><h3>Dr. David<br />Rosenbaum</h3><p>Trusted specialty care with decades of experience.</p></div></article><article className="doc two"><div><small>Endodontist</small><h3>Dr. Carl<br />Rex</h3><p>Modern treatment with a thoughtful approach.</p></div></article></div></section>
      <section className="section office" id="office"><div className="container resource-grid"><div><small className="eyebrow">Office information</small><h2>Plan your visit<br /><em>with confidence.</em></h2><p>Our Northbrook office is easy to find, with a clear schedule and direct contact information.</p><a className="link" href="https://maps.google.com/?q=1500+Shermer+Rd+Northbrook+IL+60062" target="_blank" rel="noreferrer">Get directions <ArrowRight size={16} /></a></div><div className="hours-card"><h3>Office hours</h3><div><span>Sunday</span><strong>Closed</strong></div><div><span>Monday</span><strong>8:30 AM–5 PM</strong></div><div><span>Tuesday</span><strong>8:30 AM–5 PM</strong></div><div><span>Wednesday</span><strong>Closed</strong></div><div><span>Thursday</span><strong>8:30 AM–5 PM</strong></div><div><span>Friday</span><strong>8 AM–1 PM</strong></div><div><span>Saturday</span><strong>Closed</strong></div></div></div></section>
      <section className="section resources" id="patients"><div className="container"><div className="heading"><div><small className="eyebrow">New patients</small><h2>Prepare before<br /><em>your first visit.</em></h2></div><p>Complete these editable PDFs in advance to help your first visit move smoothly.</p></div><div className="resource-cards"><a href="/forms/patient-registration-editable.pdf" target="_blank" rel="noreferrer"><span>PDF form</span><h3>Patient registration</h3><p>Contact details, insurance, and emergency information.</p><strong>Open editable form <ArrowRight size={15} /></strong></a><a href="/forms/medical-dental-history-editable.pdf" target="_blank" rel="noreferrer"><span>PDF form</span><h3>Medical & dental history</h3><p>Health history and dental history on one editable form.</p><strong>Open editable form <ArrowRight size={15} /></strong></a><a href="/forms/hipaa-notice-2026-editable.pdf" target="_blank" rel="noreferrer"><span>Updated February 2026</span><h3>HIPAA notice</h3><p>Review the updated privacy notice and complete the acknowledgment.</p><strong>Open editable form <ArrowRight size={15} /></strong></a></div></div></section>
      <section className="section referring" id="referring"><div className="container resource-grid"><div><small className="eyebrow">For referring doctors</small><h2>A clear handoff<br /><em>for your patients.</em></h2><p>Share our referral card with patients who need specialized endodontic care. We’ll keep communication clear and timely.</p><a className="button dark" href="/assets/referral-card.jpg" target="_blank" rel="noreferrer">Open referral card <ArrowRight size={17} /></a></div><a className="referral-preview" href="/assets/referral-card.jpg" target="_blank" rel="noreferrer"><img src="/assets/referral-card.jpg" alt="North Shore Endodontics referral card" /></a></div></section>
      <section className="section education" id="education"><div className="container"><div className="heading"><div><small className="eyebrow">Patient education</small><h2>Understand your<br /><em>endodontic care.</em></h2></div><p>Explore practical articles about root canals, pain, and the health of your natural teeth.</p></div><div className="education-grid"><a href="https://www.northshoreendo.com/articles/general/504140-about-pain" target="_blank" rel="noreferrer"><span>01</span><h3>About dental pain</h3><p>Learn how endodontic pain can present and when to call.</p><ArrowRight size={17} /></a><a href="https://www.northshoreendo.com/articles/general/504141-abscessed-tooth" target="_blank" rel="noreferrer"><span>02</span><h3>Abscessed tooth</h3><p>Understand the signs and why prompt care matters.</p><ArrowRight size={17} /></a><a href="https://www.northshoreendo.com/articles/general/504145-alternatives" target="_blank" rel="noreferrer"><span>03</span><h3>Alternatives to treatment</h3><p>Review the choices that may follow a diagnosis.</p><ArrowRight size={17} /></a></div></div></section>
      <section className="section visit" id="visit"><div className="container visit-in"><div><small className="eyebrow">Start your visit</small><h2>Clear answers.<br /><em>Comfortable care.</em></h2><p>Call our office directly and our team will help you understand the next step for your care.</p><ContactLink /></div><div className="steps">{[['01', 'Call our office', 'Speak with our team during office hours.'], ['02', 'Get clear guidance', 'We’ll answer your questions and explain what to expect.'], ['03', 'Feel confident moving forward', 'You’ll have a clear plan for your next visit.']].map(([number, title, text]) => <div key={number}><b>{number}</b><span><strong>{title}</strong><small>{text}</small></span></div>)}</div></div></section>
      <section className="section contact" id="contact"><div className="container contact-in"><div><small className="eyebrow">Contact us now</small><h2>Let’s get you<br /><em>feeling better.</em></h2><p>Call our Northbrook office directly. We’ll be glad to answer your questions and help you understand the next step.</p><div className="details"><a href="tel:8474801578"><Phone size={18} /> (847) 480-1578</a><span><Clock3 size={18} /> Mon–Thu, 8:00am–5:00pm</span></div></div><div className="address"><small>Visit our office</small><p>1500 Shermer Rd #300<br />Northbrook, IL 60062</p><a className="link light" href="https://maps.google.com/?q=1500+Shermer+Rd+Northbrook+IL+60062" target="_blank" rel="noreferrer">Get directions <ArrowRight size={16} /></a></div></div></section>
    </main>
    <footer><div className="container foot"><a className="brand" href="#top"><img src="/assets/northshore-logo.webp" alt="North Shore Endodontics" /></a><span>© 2026 North Shore Endodontics</span><a href="#contact">Privacy & accessibility</a></div></footer>
  </div>
}

createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>)
